# Configuration de VM3-6
- hosts: localhost
  remote_user: root
  tasks:

  # Activation du drapeau de routage IPv6
  - name: Activation du routage IPv6
    sysctl:
      name: net.ipv6.conf.all.forwarding
      value: '1'
      sysctl_set: yes

  # Suppression de la passerelle par défaut
  - name: Suppression de la passerelle par défaut
    shell: ip route del default
    ignore_errors: true

  # Configuration de la première interface
  - name: Configuration de VM3-6/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      method6: auto

  # Configuration de la deuxième interface
  - name: Configuration de VM3-6/eth2
    nmcli:
      type: ethernet
      conn_name: eth2 via ansible
      ifname: eth2
      state: present
      autoconnect: true
      ip6: fc00:1234:4::36/64

  # Route vers les autres sous réseaux IPv4
  - name: Configuration de la route vers LAN1 via VM2
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes4: 172.16.2.128/28 172.16.2.162
      state: present

  # Route vers les autres sous réseaux IPv6
  - name: Configuration de la route vers LAN2-6 via VM2-6
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes6: fc00:1234::/32 fc00:1234:2::26
      state: present

  # Activation de la première interface
  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth1 via ansible"

  # Activation de la deuxième interface
  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth2 via ansible"
