# Configuration de VM3-6
- hosts: localhost
  remote_user: root
  tasks:

  # Installation du service echo
  - name: Installation du service ECHO
    package:
      name: inetutils-inetd
      state: present

  # Configuration du service echo
  - name: Configuration du service ECHO
    shell: update-inetd --add "echo stream tcp6 nowait nobody internal"

  # Démarrage du service echo
  - name: Demarrage du service ECHO
    shell: service inetutils-inetd start

  # Redémarrage du service echo (nécessaire selon le statut)
  - name: Redemarrage du service ECHO
    shell: service inetutils-inetd restart

  # Suppression de la passerelle par défaut
  - name: Suppression de la passerelle par defaut
    shell: ip route del default || true
    ignore_errors: true

  # Configuration de la première interface
  - name: Configuration de VM3-6/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip6: fc00:1234:4::36/64

  # Route vers les autres sous réseaux
  - name: Configuration de la passerelle par defaut
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes6: ::/0 fc00:1234:4::3
      state: present

  # Activation de la première interface
  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth1 via ansible"