# Configuration de VM1-6
- hosts: localhost
  remote_user: root
  tasks:

  # Suppression de la passerelle par défaut
  - name: Suppression de la passerelle par défaut
    shell: ip route del default || true
    ignore_errors: true

  # Configuration de la première interface
  - name: Configuration de VM1-6/eth1
    nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      state: present
      autoconnect: true
      ip6: fc00:1234:3::16/64

  # Route vers les autres sous réseaux
  - name: Configuration de la passerelle par défaut
    community.general.nmcli:
      type: ethernet
      conn_name: eth1 via ansible
      ifname: eth1
      routes6: ::/0 fc00:1234:1::26
      state: present

  # Activation de la première interface
  - name: Activation explicite de cette configuration
    shell: nmcli con up "eth1 via ansible"